spring:
  application:
    name: consul-consumer  #消费者名称
  cloud:
    consul:
      host: 192.168.0.104    #consul注册节点IP
      port: 8500         #consul注册节点端口
      discovery:
        #instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}  #实例ID
        health-check-path: /consulService/health                                                       #健康检查
        health-check-interval: 10s
server:
  port: 9092   #消费者服务端口
